name: Release

on:
  push:
    branches: main
    paths:
    - 'src/**'
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Test package
        run: |
          pip install -e .[dev]
          pytest

      - name: Coverage report
        uses: codecov/codecov-action@v3

      - name: Build package
        run: python -m build
